### ISSUE TITLE
lengthOfSerializedKey should be 78

### ISSUE THREAD

**Issue by Coding-Enthusiast** [Kolibri-POS/bitcoin_bip32#1]
https://github.com/Kolibri-POS/bitcoin_bip32/blob/da9340e8c33e419c4b7b46c2ef35e7eb7a4d6434/lib/src/crypto.dart#L36

4 version + 1 depth + 4 fingerprint + 4 child number + 32 chain code + 33 public or private key = **78**

More info: https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#serialization-format

EDIT: You are not getting an error on your tests probably because you are decoding the base58 without checking and removing its 4 byte checksum. I am not familiar with this language but try the following master private key, it should not pass  your test because it has a false checksum:
`xprv9s21ZrQH143K3QTDL4LXw2F7HEK3wJUD2nW2nRk4stbPy6cq3jPPqjiChkVvvNKmPGJxWUtg6LnF5kejMRNNU3TGtRBeJgk33yuGBudW9Cd`

**Comment by Coding-Enthusiast** [comment]
Just a suggestion:
It is preferred to leave certain tasks that fall under same category to the same class. For instance in this case decoding a base58 encoded string, calculating its checksum, knowing the size of that checksum (4 byte), verifying and removing it all fall under same category and should be handled with your base58Encoder. The result is that your BIP32 class will be simplified a lot. All it knows is that the xprv... string is a base58 encoded string with a checksum so it has to call a certain function. 
I believe you are using a third party library/package, so you should look into that package for another function that does this, if it doesn't have you still can write a wrapper that does it in another class not inside your BIP32 class. 
You are looking for a function [like this](https://github.com/Coding-Enthusiast/BitcoinTransactionTool/blob/6f4aabe2f2137fe64d0bca4d9ce7b186cce363b2/CommonLibrary/CryptoEncoders/Base58.cs#L147-L174)

**Comment by haarts** [comment]
@Coding-Enthusiast That is some excellent advice. I really appreciate it! That part could do with some extraction indeed. I've added a new issue to keep track (#2).
